### PR TITLE
#162953273 Build the log in page

### PR DESCRIPTION
**Pull request by Dave-mash**
### What does this PR do?
* Creates the log in page
### Description of Task to Be completed?
The tasks for this PR is:
* Write HTML for the log in page
* Style the log in page
### How should this be manually tested?
Clone this repository on your computer then open the files on a preferred browser

Pivotal Tracker story associated with this PR
Story-ID #162953273
Screenshot:
login

### CODE REVIEW

**Comment by jmusila** [comment]
Looks nice

**Comment by Dave-mash** [comment]
> Looks nice

Thanks Musila

**Comment by emdeechege** [comment]
Clean UI

**Comment by ceexon** [comment]
Cool UI

**Comment by Dave-mash** [comment]
Thanks everyone

**Pull request merged**
